/**
 * API Error Codes
 * These codes are returned by the API and translated on the client side.
 */
export const ERROR_CODES = {
  // Authentication errors
  AUTH_EMAIL_EXISTS: 'AUTH_EMAIL_EXISTS',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_EMAIL_NOT_VERIFIED: 'AUTH_EMAIL_NOT_VERIFIED',
  AUTH_RATE_LIMITED: 'AUTH_RATE_LIMITED',
  AUTH_SLUG_TAKEN: 'AUTH_SLUG_TAKEN',
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_EXPIRED_TOKEN: 'AUTH_EXPIRED_TOKEN',
  AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
  AUTH_WRONG_PASSWORD: 'AUTH_WRONG_PASSWORD',

  // Client errors
  CLIENT_NOT_FOUND: 'CLIENT_NOT_FOUND',
  CLIENT_SLUG_TAKEN: 'CLIENT_SLUG_TAKEN',
  CLIENT_EMAIL_TAKEN: 'CLIENT_EMAIL_TAKEN',

  // Link errors
  LINK_NOT_FOUND: 'LINK_NOT_FOUND',
  LINK_LIMIT_REACHED: 'LINK_LIMIT_REACHED',

  // Publish errors
  PUBLISH_IN_PROGRESS: 'PUBLISH_IN_PROGRESS',
  PUBLISH_FAILED: 'PUBLISH_FAILED',

  // Validation errors
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  VALIDATION_EMAIL_INVALID: 'VALIDATION_EMAIL_INVALID',
  VALIDATION_PASSWORD_TOO_SHORT: 'VALIDATION_PASSWORD_TOO_SHORT',
  VALIDATION_PASSWORDS_NOT_MATCH: 'VALIDATION_PASSWORDS_NOT_MATCH',
  VALIDATION_SLUG_INVALID: 'VALIDATION_SLUG_INVALID',
  VALIDATION_URL_INVALID: 'VALIDATION_URL_INVALID',

  // Generic errors
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
} as const;

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];

/**
 * Check if a string is a valid error code
 */
export function isErrorCode(code: string): code is ErrorCode {
  return Object.values(ERROR_CODES).includes(code as ErrorCode);
}
